name: deploy

on:
    push:
        branches:
            - main

jobs:
    gh-pages:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3

            - name: Install Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: 18.x

            - name: Get yarn cache directory path
              id: yarn-cache-dir-path
              run: echo "::set-output name=dir::$(yarn config get cacheFolder)"

            - name: Restore yarn cache
              uses: actions/cache@v3
              id: yarn-cache
              with:
                  path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
                  key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
                  restore-keys: |
                      ${{ runner.os }}-yarn-

            - name: Install dependencies
              run: yarn

            - name: Deploy apps
              run: yarn deploy

            - name: Publish on Github Pages
              uses: crazy-max/ghaction-github-pages@v2.5.0
              with:
                  build_dir: out
                  jekyll: false
                  fqdn: explorer.semaphore.appliedzkp.org
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
